class ParallelismMode:
    PARALLELISM_MODE_MULTIPROCESS = 0
    PARALLELISM_MODE_THREADPOOL = 1

    ALLOWED_PARALLELISM_MODES = [
        PARALLELISM_MODE_MULTIPROCESS,
        PARALLELISM_MODE_THREADPOOL
    ]